version: '3'

services:
  app:
    container_name: docker-node-express-yarn
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules # Remove this if you have pure JS dependencies
    ports:
      - "3000:3000"